#!/usr/bin/perl -T

# needrestart-dbus - DBus interface for needrestart
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use Net::DBus;
use Net::DBus::Service;
use Net::DBus::Reactor;

use warnings;
use strict;



package NeedRestart::DBus;

use NeedRestart;
use Net::DBus::Exporter qw(net.ibh.needrestart.system);
use base qw(Net::DBus::Object);

sub new {
    my $class = shift;
    my $service = shift;

    my $self = $class->SUPER::new($service, "/net/ibh/needrestart/system");
    bless $self, $class;

    return $self;
}

dbus_method(q(GetImplementation), [], [[q(struct), q(string), q(string)]]);
sub GetImplementation {
    my $self = shift;
    my $message = shift;

    return [q(needrestart), $NeedRestart::VERSION];
}



package main;

NeedRestart::DBus->new( Net::DBus->session->export_service("net.ibh.needrestart.system") );
Net::DBus::Reactor->main->run();
